### ISSUE TITLE
Logo and website title not taking effect 

### ISSUE THREAD

**Issue by generare** [libracore/PageMaster#40]
Trying to change the website logo, it’s get saved but the visible logo is still “libracore”.

I also changed in the header settings website title but that didn’t change either.

Browser refresh doesn’t help neither the “reload” of erpnext.

**Comment by generare** [comment]
Neither the website description gets visible but it saves it in the settings though as the others.

**Comment by joelios** [comment]
split in two issues:
1. #40 = Trying to change the website logo, it’s get saved but the visible logo is still “libracore”.
2. #43  = I also changed in the header settings website title but that didn’t change either. Neither the website description gets visible but it saves it in the settings though as the others.
